sharedWorkspaceLockfile: false
minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320
shellEmulator: true

patchedDependencies:
  '@nuxt/test-utils@4.2.0': patches/@nuxt__test-utils@4.2.0.patch
  nitro@3.0.260610-beta: patches/nitro@3.0.260610-beta.patch

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
