type BadUserInputError implements Error {
  message: String!
}

type ConflictError implements Error {
  message: String!
}

type CountEvent {
  createdAt: Date!
  id: ID!
  user: User!
}

scalar Date

interface Error {
  message: String!
}

type InvalidCredentialsError implements Error {
  message: String!
}

type Mutation {
  recordCount: MutationRecordCountResult!
  signInEmail(input: SignInEmailInput!): MutationSignInEmailResult!
  signOut: MutationSignOutResult!
  signUpEmail(input: SignUpEmailInput!): MutationSignUpEmailResult!
}

union MutationRecordCountResult = RecordCountPayload | UnauthorizedError

union MutationSignInEmailResult = BadUserInputError | InvalidCredentialsError | RateLimitedError | SignInEmailPayload

union MutationSignOutResult = RateLimitedError | SignOutPayload

union MutationSignUpEmailResult = BadUserInputError | ConflictError | RateLimitedError | SignUpEmailPayload

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Query {
  count: QueryCountResult!
  countEvents(after: String, before: String, first: Int, last: Int): QueryCountEventsResult!
  session: Session
}

type QueryCountEventsConnection {
  edges: [QueryCountEventsConnectionEdge!]!
  pageInfo: PageInfo!
}

type QueryCountEventsConnectionEdge {
  cursor: String!
  node: CountEvent!
}

union QueryCountEventsResult = QueryCountEventsConnection | UnauthorizedError

union QueryCountResult = QueryCountSuccess | UnauthorizedError

type QueryCountSuccess {
  data: Int!
}

type RateLimitedError implements Error {
  message: String!
}

type RecordCountPayload {
  countEvent: CountEvent!
  totalCount: Int!
}

type Session {
  user: User!
}

input SignInEmailInput {
  email: String!
  password: String!
  rememberMe: Boolean
}

type SignInEmailPayload {
  user: User!
}

type SignOutPayload {
  ok: Boolean!
}

input SignUpEmailInput {
  email: String!
  name: String!
  password: String!
  rememberMe: Boolean
}

type SignUpEmailPayload {
  user: User!
}

scalar UUID

type UnauthorizedError implements Error {
  message: String!
}

type User {
  email: String!
  id: ID!
  name: String!
}