type CountEvent {
  createdAt: Date!
  id: ID!
  user: User!
}

scalar Date

interface Error {
  message: String!
}

type Mutation {
  recordCount: MutationRecordCountResult!
}

union MutationRecordCountResult = RecordCountPayload | UnauthorizedError

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Query {
  count: QueryCountResult!
  countEvents(after: String, before: String, first: Int, last: Int): QueryCountEventsResult!
}

type QueryCountEventsConnection {
  edges: [QueryCountEventsConnectionEdge!]!
  pageInfo: PageInfo!
}

type QueryCountEventsConnectionEdge {
  cursor: String!
  node: CountEvent!
}

union QueryCountEventsResult = QueryCountEventsConnection | UnauthorizedError

union QueryCountResult = QueryCountSuccess | UnauthorizedError

type QueryCountSuccess {
  data: Int!
}

type RecordCountPayload {
  countEvent: CountEvent!
  totalCount: Int!
}

scalar UUID

type UnauthorizedError implements Error {
  message: String!
}

type User {
  email: String!
  id: ID!
  name: String!
}