input CreateTodoInput {
  title: String!
}

scalar Date

input DeleteTodoInput {
  id: ID!
}

type DeleteTodoPayload {
  id: ID
  success: Boolean
}

type Mutation {
  createTodo(input: CreateTodoInput!): Todo
  deleteTodo(input: DeleteTodoInput!): DeleteTodoPayload
  updateTodo(input: UpdateTodoInput!): Todo
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Query {
  todo(id: ID!): Todo
  todos(after: String, before: String, first: Int, last: Int): QueryTodosConnection
}

type QueryTodosConnection {
  edges: [QueryTodosConnectionEdge]
  pageInfo: PageInfo!
}

type QueryTodosConnectionEdge {
  cursor: String!
  node: Todo
}

type Todo {
  completed: Boolean
  createdAt: Date
  id: ID
  title: String
  updatedAt: Date
}

scalar UUID

input UpdateTodoInput {
  completed: Boolean
  id: ID!
  title: String
}