import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { getAutoImportOptions } from '~/plugins/auto-import/index'

const rootDir = resolve(import.meta.dirname, '../../../../')

describe('getAutoImportOptions', () => {
  it('declares the app presets, app dirs, and plugin runtime globs', () => {
    const options = getAutoImportOptions()

    expect(options.imports).toEqual([
      'vue',
      'vue-router',
      { '@unhead/vue': ['useHead'] },
    ])
    expect(options.dirs).toEqual([
      'app/composables',
      'app/utils',
      'plugins/*/runtime/app/composables/*.ts',
      'plugins/*/runtime/app/utils/*.ts',
    ])
    // The tsconfig plugin includes `.generated/app/**/*.ts`, so the dts must
    // keep living there to stay visible to typecheck.
    expect(options.dts).toBe('.generated/app/auto-imports.d.ts')
  })
})

describe('generated auto-imports.d.ts', () => {
  // Regenerated by `pnpm prepare`, which every lint/typecheck/test workflow
  // runs through install — the file is part of the checked-in build contract.
  const dts = readFileSync(resolve(rootDir, '.generated/app/auto-imports.d.ts'), 'utf8')

  it('carries no @nuxt/ui runtime composables from node_modules', () => {
    // The takeover reason: @nuxt/ui's autoImport option appends its own
    // composables via defu and cannot drop them otherwise.
    expect(dts).not.toContain('node_modules')
  })

  it('exposes plugin runtime composables like useAppContext', () => {
    expect(dts).toContain(
      `typeof import('../../plugins/vue-ssr/runtime/app/composables/useAppContext')`,
    )
  })

  it('keeps the app surface (presets, @unhead/vue, app utils)', () => {
    expect(dts).toContain(`typeof import('vue').computed`)
    expect(dts).toContain(`typeof import('vue-router').useRoute`)
    expect(dts).toContain(`typeof import('@unhead/vue').useHead`)
    expect(dts).toContain(
      `typeof import('../../app/utils/format-when').formatWhen`,
    )
  })
})
